AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Signup

Globals:
  Api:
    Cors:
      AllowHeaders: "'x-requested-with'"
      AllowOrigin: "'http://serverless-signup.s3-website-eu-west-1.amazonaws.com'"

Resources:

  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Timeout: 10
      MemorySize: 1024
      Environment:
        Variables:
          STARTUP_SIGNUP_TABLE: !Ref StartupSignupsTable
          NEW_SIGNUP_TOPIC: !Ref NewSignupTopic
      Events:
        PostAPI:
          Type: Api
          Properties:
            Path: /signup
            Method: post
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt StartupSignupsTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref NewSignupTopic
    
  StartupSignupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        HashKeyElement: {AttributeName: email, AttributeType: S}
      ProvisionedThroughput: {ReadCapacityUnits: 1, WriteCapacityUnits: 1}

  NewSignupQueue: 
    Type: AWS::SQS::Queue

  NewSignupTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: alex@alexcasalboni.com
        Protocol: email
      - Endpoint:
          Fn::GetAtt: [NewSignupQueue, Arn]
        Protocol: sqs

  AllowSNS2SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: PublicationPolicy
        Statement:
        - Action: ['sqs:SendMessage']
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref NewSignupTopic
          Effect: Allow
          Principal: {AWS: '*'}
          Resource:
            Fn::GetAtt: [NewSignupQueue, Arn]
          Sid: Allow-SNS-SendMessage
        Version: '2008-10-17'
      Queues:
      - {Ref: NewSignupQueue}
